// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WhoWantsToBeAMillionaire.Model;

namespace WhoWantsToBeAMillionaire.Migrations
{
    [DbContext(typeof(MillionaireContext))]
    partial class MillionaireContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.24");

            modelBuilder.Entity("WhoWantsToBeAMillionaire.Model.DBAchievement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Achieve")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Achievements");
                });

            modelBuilder.Entity("WhoWantsToBeAMillionaire.Model.DBQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("QAnswerA")
                        .HasColumnType("TEXT");

                    b.Property<string>("QAnswerB")
                        .HasColumnType("TEXT");

                    b.Property<string>("QAnswerC")
                        .HasColumnType("TEXT");

                    b.Property<string>("QAnswerD")
                        .HasColumnType("TEXT");

                    b.Property<int>("QLevel")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QRightAnswer")
                        .HasColumnType("INTEGER");

                    b.Property<string>("QText")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Questions");
                });
#pragma warning restore 612, 618
        }
    }
}
